### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/express-multer#3]
`express-middleware-multer`

Any opinions?

**Comment by jrhorn424** [comment]
Maybe just `express-multer` since middleware is implied?

**Comment by gaand** [comment]
I almost renamed it to `express-multer-aws` just a moment ago.  Then it occurred to me that maybe we should have a `node-aws` lesson and then an `express-multer` lesson.  For now I'm going with `express-multer` and opening an issue about maybe creating a `node-aws` lesson.

**Comment by jrhorn424** [comment]
I like that idea.
